#pragma once

#include "stdint.h"
typedef enum
{
    // MSG FROM NEXTION RX TO MAIN TASK
    HOME_LOADED,
    HOME_TARA_1_ENABLED,
    HOME_TARA_1_DISABLED,
    HOME_TARA_2_ENABLED,
    HOME_TARA_2_DISABLED,
    HOME_TARA_3_ENABLED,
    HOME_TARA_3_DISABLED,
    HOME_TARA_4_ENABLED,
    HOME_TARA_4_DISABLED,
    SYSTEM_SETTINGS_LOADED,
    CALIBRATION_LOADED,
    CALIBRATION_SWITCH_1_ENABLED,
    CALIBRATION_SWITCH_1_DISABLED,
    CALIBRATION_SWITCH_2_ENABLED,
    CALIBRATION_SWITCH_2_DISABLED,
    CALIBRATION_SWITCH_3_ENABLED,
    CALIBRATION_SWITCH_3_DISABLED,
    CALIBRATION_SWITCH_4_ENABLED,
    CALIBRATION_SWITCH_4_DISABLED,
    CALIBRATION_SWITCH_5_ENABLED,
    CALIBRATION_SWITCH_5_DISABLED,
    CALIBRATION_SWITCH_6_ENABLED,
    CALIBRATION_SWITCH_6_DISABLED,
    CALIBRATION_SWITCH_7_ENABLED,
    CALIBRATION_SWITCH_7_DISABLED,
    CALIBRATION_SWITCH_8_ENABLED,
    CALIBRATION_SWITCH_8_DISABLED,
    CALIBRATION_SENSOR_1_UNIT_CHANGED,
    CALIBRATION_SENSOR_2_UNIT_CHANGED,
    CALIBRATION_SENSOR_3_UNIT_CHANGED,
    CALIBRATION_SENSOR_4_UNIT_CHANGED,

    INPUTCALIBP1_LOADED,
    INPUTCALIBP1_TYPE_RECEIVED,
    INPUTCALIBP1_CAPACITY_RECEIVED,
    INPUTCALIBP1_CAPACITY_UNIT_RECEIVED,
    INPUTCALIBP1_SENSIBILITY_RECEIVED,
    INPUTCALIBP1_SENSIBILITY_UNIT_RECEIVED,
    INPUTCALIBP1_SENSOR_INDEX_RECEIVED,
    INPUTCALIBP2_LOADED,
    INPUTCALIBP2_CALIBRATION_LIMIT_RECEIVED,
    INPUTCALIBP2_CALIBRATION_LIMIT_UNIT_RECEIVED,
    INPUTCALIBP2_LIMIT_ENABLE_RECEIVED,
    INPUTCALIBP3_LOADED,
    INPUTCALIBP3_TABLE_RECEIVED,
    INPUTCALIBP3_NUM_POINTS_RECEIVED,
    INPUTCALIBP3_ROW_TO_FILL_RECEIVED,
    INPUTCALIBP4_LOADED,
    INPUTCALIBP4_NAME_RECEIVED,
    INPUTCALIBP4_SAVE_PRESSED,

    NUMPAD_POPUP_LOADED,

    EXTERNAL_SENSOR_5_UNIT_CHANGED,
    EXTERNAL_SENSOR_6_UNIT_CHANGED,
    EXTERNAL_SENSOR_7_UNIT_CHANGED,
    EXTERNAL_SENSOR_8_UNIT_CHANGED,
    EXTERNAL_SENSOR_5_UNITPS_CHANGED,
    EXTERNAL_SENSOR_6_UNITPS_CHANGED,
    EXTERNAL_SENSOR_7_UNITPS_CHANGED,
    EXTERNAL_SENSOR_8_UNITPS_CHANGED,

    //
    NEXTION_UPDATE,

} msg_type_t;

typedef enum
{
    HOME = 0,
    SYSTEM_SETTINGS,
    CALIBRATION,
    INPUTCALIBP1,
    INPUTCALIBP2,
    INPUTCALIBP3,
    INPUTCALIBP4,
    NUMPAD_POPUP,
} page_t;

typedef struct
{
    msg_type_t type;
    union
    {
        uint32_t u32;
        float f32;
        int32_t i32;
        void *addr;
    } content;
    int size;
} msg_t;
